blank_issues_enabled: false
contact_links:
  - name: ⚠️ Project Deprecated - Extension No Longer Works
    url: https://github.com/liorgrossman/darkness/blob/master/DEPRECATION_NOTICE.md
    about: This project is deprecated and does not accept new issues. Read why here.
