blank_issues_enabled: false
contact_links:
  - name: 📚 Deprecation Notice
    url: https://github.com/liorgrossman/darkness/blob/master/DEPRECATION_NOTICE.md
    about: Read about why this project is deprecated
